-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 10:27:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RECIPES
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RECIPES` ;

-- -----------------------------------------------------
-- Schema RECIPES
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RECIPES` DEFAULT CHARACTER SET utf8 ;
USE `RECIPES` ;

-- -----------------------------------------------------
-- Table `RECIPES`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RECIPES`.`images` ;

CREATE TABLE IF NOT EXISTS `RECIPES`.`images` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `image_path` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RECIPES`.`videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RECIPES`.`videos` ;

CREATE TABLE IF NOT EXISTS `RECIPES`.`videos` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `video_path` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RECIPES`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RECIPES`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `RECIPES`.`ingredients` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ingredient_name` VARCHAR(45) NOT NULL,
  `ingr_image_id` INT NULL DEFAULT NULL,
  `nutrition_fact_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ingr_image_id_idx` (`ingr_image_id` ASC),
  CONSTRAINT `ingr_image_id`
    FOREIGN KEY (`ingr_image_id`)
    REFERENCES `RECIPES`.`images` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RECIPES`.`recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RECIPES`.`recipes` ;

CREATE TABLE IF NOT EXISTS `RECIPES`.`recipes` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `recipe_name` VARCHAR(45) NOT NULL,
  `image_id` INT NOT NULL,
  `video_id` INT NULL DEFAULT NULL,
  `likes` INT NULL DEFAULT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `image_id_idx` (`image_id` ASC),
  INDEX `video_id_idx` (`video_id` ASC),
  CONSTRAINT `image_id`
    FOREIGN KEY (`image_id`)
    REFERENCES `RECIPES`.`images` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `video_id`
    FOREIGN KEY (`video_id`)
    REFERENCES `RECIPES`.`videos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RECIPES`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RECIPES`.`users` ;

CREATE TABLE IF NOT EXISTS `RECIPES`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `user_image_paht` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RECIPES`.`recipe_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RECIPES`.`recipe_ingredients` ;

CREATE TABLE IF NOT EXISTS `RECIPES`.`recipe_ingredients` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ri_recipe_id` INT NOT NULL,
  `ri_ingredient_id` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `recipe_id_idx` (`ri_recipe_id` ASC),
  INDEX `ingredient_id_idx` (`ri_ingredient_id` ASC),
  CONSTRAINT `ri_recipe_id`
    FOREIGN KEY (`ri_recipe_id`)
    REFERENCES `RECIPES`.`recipes` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ri_ingredient_id`
    FOREIGN KEY (`ri_ingredient_id`)
    REFERENCES `RECIPES`.`ingredients` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RECIPES`.`user_recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RECIPES`.`user_recipes` ;

CREATE TABLE IF NOT EXISTS `RECIPES`.`user_recipes` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ur_user_id` INT NOT NULL,
  `ur_recipe_id` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ur_user_id_idx` (`ur_user_id` ASC),
  INDEX `ur_recipe_id_idx` (`ur_recipe_id` ASC),
  CONSTRAINT `ur_user_id`
    FOREIGN KEY (`ur_user_id`)
    REFERENCES `RECIPES`.`users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ur_recipe_id`
    FOREIGN KEY (`ur_recipe_id`)
    REFERENCES `RECIPES`.`recipes` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;